# AUTOGENERATED BY NBDEV! DO NOT EDIT!

__all__ = ["index", "modules", "custom_doc_links", "git_url"]

index = {}

modules = []

doc_url = "https://daniellinder.github.io/scaffold/"

git_url = "https://github.com/daniellinder/scaffold/tree/{branch}/"

def custom_doc_links(name): return None
